//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 01:29:02 EDT 
//


package edu.uconn.psy.jtrace.parser;


/**
 * Java content class for jtConditionalType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 190)
 * <p>
 * <pre>
 * &lt;complexType name="jtConditionalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="if" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
 *         &lt;element name="then" type="{http://xml.netbeans.org/examples/targetNS}jtExpressionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JtConditionalType {


    /**
     * Gets the value of the Then property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Then property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link edu.uconn.psy.jtrace.parser.JtExpressionType}
     * 
     */
    java.util.List getThen();

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType getIf();

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
     */
    void setIf(edu.uconn.psy.jtrace.parser.JtPredicateType value);

}
