//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 01:29:02 EDT 
//


package edu.uconn.psy.jtrace.parser;


/**
 * Java content class for jtExpressionType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 37)
 * <p>
 * <pre>
 * &lt;complexType name="jtExpressionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="iterate" type="{http://xml.netbeans.org/examples/targetNS}jtIteratorType"/>
 *         &lt;element name="condition" type="{http://xml.netbeans.org/examples/targetNS}jtConditionalType"/>
 *         &lt;element name="action" type="{http://xml.netbeans.org/examples/targetNS}jtActionType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JtExpressionType {


    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtActionType}
     */
    edu.uconn.psy.jtrace.parser.JtActionType getAction();

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtActionType}
     */
    void setAction(edu.uconn.psy.jtrace.parser.JtActionType value);

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtConditionalType}
     */
    edu.uconn.psy.jtrace.parser.JtConditionalType getCondition();

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtConditionalType}
     */
    void setCondition(edu.uconn.psy.jtrace.parser.JtConditionalType value);

    /**
     * Gets the value of the iterate property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtIteratorType}
     */
    edu.uconn.psy.jtrace.parser.JtIteratorType getIterate();

    /**
     * Sets the value of the iterate property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtIteratorType}
     */
    void setIterate(edu.uconn.psy.jtrace.parser.JtIteratorType value);

}
