//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 01:29:02 EDT 
//


package edu.uconn.psy.jtrace.parser;


/**
 * Java content class for jtPredicateType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 198)
 * <p>
 * <pre>
 * &lt;complexType name="jtPredicateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="equals">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                   &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="not-equal">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                   &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="is-greater-than">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                   &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="is-less-than">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                   &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="is-member-of-list">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="search-item" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                   &lt;element name="list" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="true">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="arg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="false">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="arg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="and">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="predicate-one" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
 *                   &lt;element name="predicate-two" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="or">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="predicate-one" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
 *                   &lt;element name="predicate-two" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="not">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="predicate-one" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JtPredicateType {


    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.OrType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.OrType getOr();

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.OrType}
     */
    void setOr(edu.uconn.psy.jtrace.parser.JtPredicateType.OrType value);

    /**
     * Gets the value of the isGreaterThan property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.IsGreaterThanType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.IsGreaterThanType getIsGreaterThan();

    /**
     * Sets the value of the isGreaterThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.IsGreaterThanType}
     */
    void setIsGreaterThan(edu.uconn.psy.jtrace.parser.JtPredicateType.IsGreaterThanType value);

    /**
     * Gets the value of the notEqual property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.NotEqualType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.NotEqualType getNotEqual();

    /**
     * Sets the value of the notEqual property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.NotEqualType}
     */
    void setNotEqual(edu.uconn.psy.jtrace.parser.JtPredicateType.NotEqualType value);

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.AndType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.AndType getAnd();

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.AndType}
     */
    void setAnd(edu.uconn.psy.jtrace.parser.JtPredicateType.AndType value);

    /**
     * Gets the value of the false property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.FalseType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.FalseType getFalse();

    /**
     * Sets the value of the false property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.FalseType}
     */
    void setFalse(edu.uconn.psy.jtrace.parser.JtPredicateType.FalseType value);

    /**
     * Gets the value of the true property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.TrueType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.TrueType getTrue();

    /**
     * Sets the value of the true property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.TrueType}
     */
    void setTrue(edu.uconn.psy.jtrace.parser.JtPredicateType.TrueType value);

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.NotType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.NotType getNot();

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.NotType}
     */
    void setNot(edu.uconn.psy.jtrace.parser.JtPredicateType.NotType value);

    /**
     * Gets the value of the equals property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.EqualsType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.EqualsType getEquals();

    /**
     * Sets the value of the equals property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.EqualsType}
     */
    void setEquals(edu.uconn.psy.jtrace.parser.JtPredicateType.EqualsType value);

    /**
     * Gets the value of the isMemberOfList property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.IsMemberOfListType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.IsMemberOfListType getIsMemberOfList();

    /**
     * Sets the value of the isMemberOfList property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.IsMemberOfListType}
     */
    void setIsMemberOfList(edu.uconn.psy.jtrace.parser.JtPredicateType.IsMemberOfListType value);

    /**
     * Gets the value of the isLessThan property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.IsLessThanType}
     */
    edu.uconn.psy.jtrace.parser.JtPredicateType.IsLessThanType getIsLessThan();

    /**
     * Sets the value of the isLessThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType.IsLessThanType}
     */
    void setIsLessThan(edu.uconn.psy.jtrace.parser.JtPredicateType.IsLessThanType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 241)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="predicate-one" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
     *         &lt;element name="predicate-two" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface AndType {


        /**
         * Gets the value of the predicateTwo property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        edu.uconn.psy.jtrace.parser.JtPredicateType getPredicateTwo();

        /**
         * Sets the value of the predicateTwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        void setPredicateTwo(edu.uconn.psy.jtrace.parser.JtPredicateType value);

        /**
         * Gets the value of the predicateOne property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        edu.uconn.psy.jtrace.parser.JtPredicateType getPredicateOne();

        /**
         * Sets the value of the predicateOne property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        void setPredicateOne(edu.uconn.psy.jtrace.parser.JtPredicateType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 201)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *         &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface EqualsType {


        /**
         * Gets the value of the two property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getTwo();

        /**
         * Sets the value of the two property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setTwo(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

        /**
         * Gets the value of the one property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getOne();

        /**
         * Sets the value of the one property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setOne(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 236)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="arg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface FalseType {


        /**
         * Gets the value of the arg property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getArg();

        /**
         * Sets the value of the arg property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setArg(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 213)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *         &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface IsGreaterThanType {


        /**
         * Gets the value of the two property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getTwo();

        /**
         * Sets the value of the two property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setTwo(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

        /**
         * Gets the value of the one property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getOne();

        /**
         * Sets the value of the one property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setOne(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 219)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *         &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface IsLessThanType {


        /**
         * Gets the value of the two property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getTwo();

        /**
         * Sets the value of the two property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setTwo(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

        /**
         * Gets the value of the one property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getOne();

        /**
         * Sets the value of the one property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setOne(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 225)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="search-item" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *         &lt;element name="list" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface IsMemberOfListType {


        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getList();

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setList(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

        /**
         * Gets the value of the searchItem property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getSearchItem();

        /**
         * Sets the value of the searchItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setSearchItem(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 207)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="one" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *         &lt;element name="two" type="{http://xml.netbeans.org/examples/targetNS}jtPrimitiveType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface NotEqualType {


        /**
         * Gets the value of the two property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getTwo();

        /**
         * Sets the value of the two property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setTwo(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

        /**
         * Gets the value of the one property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        edu.uconn.psy.jtrace.parser.JtPrimitiveType getOne();

        /**
         * Sets the value of the one property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPrimitiveType}
         */
        void setOne(edu.uconn.psy.jtrace.parser.JtPrimitiveType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 253)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="predicate-one" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface NotType {


        /**
         * Gets the value of the predicateOne property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        edu.uconn.psy.jtrace.parser.JtPredicateType getPredicateOne();

        /**
         * Sets the value of the predicateOne property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        void setPredicateOne(edu.uconn.psy.jtrace.parser.JtPredicateType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 247)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="predicate-one" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
     *         &lt;element name="predicate-two" type="{http://xml.netbeans.org/examples/targetNS}jtPredicateType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface OrType {


        /**
         * Gets the value of the predicateTwo property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        edu.uconn.psy.jtrace.parser.JtPredicateType getPredicateTwo();

        /**
         * Sets the value of the predicateTwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        void setPredicateTwo(edu.uconn.psy.jtrace.parser.JtPredicateType value);

        /**
         * Gets the value of the predicateOne property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        edu.uconn.psy.jtrace.parser.JtPredicateType getPredicateOne();

        /**
         * Sets the value of the predicateOne property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtPredicateType}
         */
        void setPredicateOne(edu.uconn.psy.jtrace.parser.JtPredicateType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 231)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="arg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface TrueType {


        /**
         * Gets the value of the arg property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getArg();

        /**
         * Sets the value of the arg property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setArg(java.lang.String value);

    }

}
