//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 01:29:02 EDT 
//


package edu.uconn.psy.jtrace.parser;


/**
 * Java content class for jtQueryType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 495)
 * <p>
 * <pre>
 * &lt;complexType name="jtQueryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="item-with-highest-peak">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="fetch-current-value-of-a-parameter">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="parameter-name" type="{http://xml.netbeans.org/examples/targetNS}jtModifiableParameterLabelsType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="current-input">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="size-of-lexicon">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="nth-item-in-lexicon">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="N" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="query-one-simulation-cell">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="layer">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;element name="word-layer">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="word" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
 *                                         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="phoneme-layer">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="phoneme" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
 *                                         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="feature-layer">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
 *                                         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="input-layer">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
 *                                         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="value-of-highest-peak">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="item-with-nth-highest-peak">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="value-of-nth-highest-peak">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="peak-value-of-item">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="arg" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="cycle-when-item-peaks">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="item" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="cycle-when-item-exceeds-threshold">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="item" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
 *                     &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="nth-item-to-exceed-threshold">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="decision-rule-report">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                     &lt;element name="item" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
 *                     &lt;element name="verbosity">
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="McClellend-1991-running-average-metric">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="phoneme-one" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
 *                     &lt;element name="phoneme-two" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
 *                     &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="lambda" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                     &lt;element name="initial-value" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JtQueryType {


    /**
     * Gets the value of the peakValueOfItem property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.PeakValueOfItemType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.PeakValueOfItemType getPeakValueOfItem();

    /**
     * Sets the value of the peakValueOfItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.PeakValueOfItemType}
     */
    void setPeakValueOfItem(edu.uconn.psy.jtrace.parser.JtQueryType.PeakValueOfItemType value);

    /**
     * Gets the value of the mcClellend1991RunningAverageMetric property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.McClellend1991RunningAverageMetricType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.McClellend1991RunningAverageMetricType getMcClellend1991RunningAverageMetric();

    /**
     * Sets the value of the mcClellend1991RunningAverageMetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.McClellend1991RunningAverageMetricType}
     */
    void setMcClellend1991RunningAverageMetric(edu.uconn.psy.jtrace.parser.JtQueryType.McClellend1991RunningAverageMetricType value);

    /**
     * Gets the value of the valueOfNthHighestPeak property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfNthHighestPeakType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfNthHighestPeakType getValueOfNthHighestPeak();

    /**
     * Sets the value of the valueOfNthHighestPeak property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfNthHighestPeakType}
     */
    void setValueOfNthHighestPeak(edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfNthHighestPeakType value);

    /**
     * Gets the value of the sizeOfLexicon property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.SizeOfLexiconType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.SizeOfLexiconType getSizeOfLexicon();

    /**
     * Sets the value of the sizeOfLexicon property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.SizeOfLexiconType}
     */
    void setSizeOfLexicon(edu.uconn.psy.jtrace.parser.JtQueryType.SizeOfLexiconType value);

    /**
     * Gets the value of the decisionRuleReport property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.DecisionRuleReportType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.DecisionRuleReportType getDecisionRuleReport();

    /**
     * Sets the value of the decisionRuleReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.DecisionRuleReportType}
     */
    void setDecisionRuleReport(edu.uconn.psy.jtrace.parser.JtQueryType.DecisionRuleReportType value);

    /**
     * Gets the value of the queryOneSimulationCell property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType getQueryOneSimulationCell();

    /**
     * Sets the value of the queryOneSimulationCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType}
     */
    void setQueryOneSimulationCell(edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType value);

    /**
     * Gets the value of the itemWithHighestPeak property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithHighestPeakType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithHighestPeakType getItemWithHighestPeak();

    /**
     * Sets the value of the itemWithHighestPeak property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithHighestPeakType}
     */
    void setItemWithHighestPeak(edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithHighestPeakType value);

    /**
     * Gets the value of the nthItemInLexicon property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.NthItemInLexiconType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.NthItemInLexiconType getNthItemInLexicon();

    /**
     * Sets the value of the nthItemInLexicon property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.NthItemInLexiconType}
     */
    void setNthItemInLexicon(edu.uconn.psy.jtrace.parser.JtQueryType.NthItemInLexiconType value);

    /**
     * Gets the value of the fetchCurrentValueOfAParameter property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.FetchCurrentValueOfAParameterType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.FetchCurrentValueOfAParameterType getFetchCurrentValueOfAParameter();

    /**
     * Sets the value of the fetchCurrentValueOfAParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.FetchCurrentValueOfAParameterType}
     */
    void setFetchCurrentValueOfAParameter(edu.uconn.psy.jtrace.parser.JtQueryType.FetchCurrentValueOfAParameterType value);

    /**
     * Gets the value of the itemWithNthHighestPeak property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithNthHighestPeakType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithNthHighestPeakType getItemWithNthHighestPeak();

    /**
     * Sets the value of the itemWithNthHighestPeak property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithNthHighestPeakType}
     */
    void setItemWithNthHighestPeak(edu.uconn.psy.jtrace.parser.JtQueryType.ItemWithNthHighestPeakType value);

    /**
     * Gets the value of the nthItemToExceedThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.NthItemToExceedThresholdType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.NthItemToExceedThresholdType getNthItemToExceedThreshold();

    /**
     * Sets the value of the nthItemToExceedThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.NthItemToExceedThresholdType}
     */
    void setNthItemToExceedThreshold(edu.uconn.psy.jtrace.parser.JtQueryType.NthItemToExceedThresholdType value);

    /**
     * Gets the value of the cycleWhenItemPeaks property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemPeaksType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemPeaksType getCycleWhenItemPeaks();

    /**
     * Sets the value of the cycleWhenItemPeaks property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemPeaksType}
     */
    void setCycleWhenItemPeaks(edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemPeaksType value);

    /**
     * Gets the value of the cycleWhenItemExceedsThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemExceedsThresholdType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemExceedsThresholdType getCycleWhenItemExceedsThreshold();

    /**
     * Sets the value of the cycleWhenItemExceedsThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemExceedsThresholdType}
     */
    void setCycleWhenItemExceedsThreshold(edu.uconn.psy.jtrace.parser.JtQueryType.CycleWhenItemExceedsThresholdType value);

    /**
     * Gets the value of the currentInput property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.CurrentInputType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.CurrentInputType getCurrentInput();

    /**
     * Sets the value of the currentInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.CurrentInputType}
     */
    void setCurrentInput(edu.uconn.psy.jtrace.parser.JtQueryType.CurrentInputType value);

    /**
     * Gets the value of the valueOfHighestPeak property.
     * 
     * @return
     *     possible object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfHighestPeakType}
     */
    edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfHighestPeakType getValueOfHighestPeak();

    /**
     * Sets the value of the valueOfHighestPeak property.
     * 
     * @param value
     *     allowed object is
     *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfHighestPeakType}
     */
    void setValueOfHighestPeak(edu.uconn.psy.jtrace.parser.JtQueryType.ValueOfHighestPeakType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 509)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CurrentInputType {


        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 591)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="item" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
     *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CycleWhenItemExceedsThresholdType {


        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        edu.uconn.psy.jtrace.parser.JtTextOrQueryType getItem();

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        void setItem(edu.uconn.psy.jtrace.parser.JtTextOrQueryType value);

        /**
         * Gets the value of the threshold property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigDecimal}
         */
        java.math.BigDecimal getThreshold();

        /**
         * Sets the value of the threshold property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigDecimal}
         */
        void setThreshold(java.math.BigDecimal value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 585)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="item" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CycleWhenItemPeaksType {


        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        edu.uconn.psy.jtrace.parser.JtTextOrQueryType getItem();

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        void setItem(edu.uconn.psy.jtrace.parser.JtTextOrQueryType value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 605)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="item" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
     *         &lt;element name="verbosity">
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *             &lt;enumeration value="1"/>
     *             &lt;enumeration value="2"/>
     *             &lt;enumeration value="3"/>
     *           &lt;/restriction>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface DecisionRuleReportType {


        /**
         * Gets the value of the verbosity property.
         * 
         */
        int getVerbosity();

        /**
         * Sets the value of the verbosity property.
         * 
         */
        void setVerbosity(int value);

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        edu.uconn.psy.jtrace.parser.JtTextOrQueryType getItem();

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        void setItem(edu.uconn.psy.jtrace.parser.JtTextOrQueryType value);

        /**
         * Gets the value of the threshold property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigDecimal}
         */
        java.math.BigDecimal getThreshold();

        /**
         * Sets the value of the threshold property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigDecimal}
         */
        void setThreshold(java.math.BigDecimal value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 504)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parameter-name" type="{http://xml.netbeans.org/examples/targetNS}jtModifiableParameterLabelsType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface FetchCurrentValueOfAParameterType {


        /**
         * Gets the value of the parameterName property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getParameterName();

        /**
         * Sets the value of the parameterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setParameterName(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 499)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ItemWithHighestPeakType {


        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 567)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ItemWithNthHighestPeakType {


        /**
         * Gets the value of the n property.
         * 
         */
        int getN();

        /**
         * Sets the value of the n property.
         * 
         */
        void setN(int value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 621)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="phoneme-one" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
     *         &lt;element name="phoneme-two" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
     *         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="lambda" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="initial-value" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface McClellend1991RunningAverageMetricType {


        /**
         * Gets the value of the initialValue property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigDecimal}
         */
        java.math.BigDecimal getInitialValue();

        /**
         * Sets the value of the initialValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigDecimal}
         */
        void setInitialValue(java.math.BigDecimal value);

        /**
         * Gets the value of the lambda property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigDecimal}
         */
        java.math.BigDecimal getLambda();

        /**
         * Sets the value of the lambda property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigDecimal}
         */
        void setLambda(java.math.BigDecimal value);

        /**
         * Gets the value of the alignment property.
         * 
         */
        int getAlignment();

        /**
         * Sets the value of the alignment property.
         * 
         */
        void setAlignment(int value);

        /**
         * Gets the value of the phonemeOne property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPhonemeOne();

        /**
         * Sets the value of the phonemeOne property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPhonemeOne(java.lang.String value);

        /**
         * Gets the value of the phonemeTwo property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPhonemeTwo();

        /**
         * Sets the value of the phonemeTwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPhonemeTwo(java.lang.String value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 519)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="N" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface NthItemInLexiconType {


        /**
         * Gets the value of the n property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        edu.uconn.psy.jtrace.parser.JtTextOrQueryType getN();

        /**
         * Sets the value of the n property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        void setN(edu.uconn.psy.jtrace.parser.JtTextOrQueryType value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 598)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface NthItemToExceedThresholdType {


        /**
         * Gets the value of the n property.
         * 
         */
        int getN();

        /**
         * Sets the value of the n property.
         * 
         */
        void setN(int value);

        /**
         * Gets the value of the threshold property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigDecimal}
         */
        java.math.BigDecimal getThreshold();

        /**
         * Sets the value of the threshold property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigDecimal}
         */
        void setThreshold(java.math.BigDecimal value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 579)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="arg" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface PeakValueOfItemType {


        /**
         * Gets the value of the arg property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        edu.uconn.psy.jtrace.parser.JtTextOrQueryType getArg();

        /**
         * Sets the value of the arg property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
         */
        void setArg(edu.uconn.psy.jtrace.parser.JtTextOrQueryType value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 525)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="layer">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="word-layer">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="word" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
     *                             &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="phoneme-layer">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="phoneme" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
     *                             &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="feature-layer">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
     *                             &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="input-layer">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
     *                             &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface QueryOneSimulationCellType {


        /**
         * Gets the value of the layer property.
         * 
         * @return
         *     possible object is
         *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType}
         */
        edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType getLayer();

        /**
         * Sets the value of the layer property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType}
         */
        void setLayer(edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 528)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="word-layer">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="word" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
         *                   &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="phoneme-layer">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="phoneme" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
         *                   &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="feature-layer">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
         *                   &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="input-layer">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
         *                   &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface LayerType {


            /**
             * Gets the value of the inputLayer property.
             * 
             * @return
             *     possible object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.InputLayerType}
             */
            edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.InputLayerType getInputLayer();

            /**
             * Sets the value of the inputLayer property.
             * 
             * @param value
             *     allowed object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.InputLayerType}
             */
            void setInputLayer(edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.InputLayerType value);

            /**
             * Gets the value of the featureLayer property.
             * 
             * @return
             *     possible object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.FeatureLayerType}
             */
            edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.FeatureLayerType getFeatureLayer();

            /**
             * Sets the value of the featureLayer property.
             * 
             * @param value
             *     allowed object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.FeatureLayerType}
             */
            void setFeatureLayer(edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.FeatureLayerType value);

            /**
             * Gets the value of the wordLayer property.
             * 
             * @return
             *     possible object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.WordLayerType}
             */
            edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.WordLayerType getWordLayer();

            /**
             * Sets the value of the wordLayer property.
             * 
             * @param value
             *     allowed object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.WordLayerType}
             */
            void setWordLayer(edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.WordLayerType value);

            /**
             * Gets the value of the phonemeLayer property.
             * 
             * @return
             *     possible object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.PhonemeLayerType}
             */
            edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.PhonemeLayerType getPhonemeLayer();

            /**
             * Sets the value of the phonemeLayer property.
             * 
             * @param value
             *     allowed object is
             *     {@link edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.PhonemeLayerType}
             */
            void setPhonemeLayer(edu.uconn.psy.jtrace.parser.JtQueryType.QueryOneSimulationCellType.LayerType.PhonemeLayerType value);


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 544)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
             *         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface FeatureLayerType {


                /**
                 * Gets the value of the feature property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getFeature();

                /**
                 * Sets the value of the feature property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setFeature(java.lang.String value);

                /**
                 * Gets the value of the cycle property.
                 * 
                 */
                int getCycle();

                /**
                 * Sets the value of the cycle property.
                 * 
                 */
                void setCycle(int value);

                /**
                 * Gets the value of the alignment property.
                 * 
                 */
                int getAlignment();

                /**
                 * Sets the value of the alignment property.
                 * 
                 */
                void setAlignment(int value);

            }


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 551)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="feature" type="{http://xml.netbeans.org/examples/targetNS}jtFeatureLabelsType"/>
             *         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface InputLayerType {


                /**
                 * Gets the value of the feature property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getFeature();

                /**
                 * Sets the value of the feature property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setFeature(java.lang.String value);

                /**
                 * Gets the value of the cycle property.
                 * 
                 */
                int getCycle();

                /**
                 * Sets the value of the cycle property.
                 * 
                 */
                void setCycle(int value);

                /**
                 * Gets the value of the alignment property.
                 * 
                 */
                int getAlignment();

                /**
                 * Sets the value of the alignment property.
                 * 
                 */
                void setAlignment(int value);

            }


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 537)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="phoneme" type="{http://xml.netbeans.org/examples/targetNS}jtPhonemeLabelsType"/>
             *         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface PhonemeLayerType {


                /**
                 * Gets the value of the phoneme property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getPhoneme();

                /**
                 * Sets the value of the phoneme property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setPhoneme(java.lang.String value);

                /**
                 * Gets the value of the cycle property.
                 * 
                 */
                int getCycle();

                /**
                 * Sets the value of the cycle property.
                 * 
                 */
                void setCycle(int value);

                /**
                 * Gets the value of the alignment property.
                 * 
                 */
                int getAlignment();

                /**
                 * Sets the value of the alignment property.
                 * 
                 */
                void setAlignment(int value);

            }


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 530)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="word" type="{http://xml.netbeans.org/examples/targetNS}jtTextOrQueryType"/>
             *         &lt;element name="alignment" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface WordLayerType {


                /**
                 * Gets the value of the word property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
                 */
                edu.uconn.psy.jtrace.parser.JtTextOrQueryType getWord();

                /**
                 * Sets the value of the word property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link edu.uconn.psy.jtrace.parser.JtTextOrQueryType}
                 */
                void setWord(edu.uconn.psy.jtrace.parser.JtTextOrQueryType value);

                /**
                 * Gets the value of the cycle property.
                 * 
                 */
                int getCycle();

                /**
                 * Sets the value of the cycle property.
                 * 
                 */
                void setCycle(int value);

                /**
                 * Gets the value of the alignment property.
                 * 
                 */
                int getAlignment();

                /**
                 * Sets the value of the alignment property.
                 * 
                 */
                void setAlignment(int value);

            }

        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 514)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface SizeOfLexiconType {


        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 562)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ValueOfHighestPeakType {


        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 573)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ValueOfNthHighestPeakType {


        /**
         * Gets the value of the n property.
         * 
         */
        int getN();

        /**
         * Sets the value of the n property.
         * 
         */
        void setN(int value);

        /**
         * Gets the value of the returnType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getReturnType();

        /**
         * Sets the value of the returnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setReturnType(java.lang.String value);

    }

}
