//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 01:29:02 EDT 
//


package edu.uconn.psy.jtrace.parser;


/**
 * Java content class for lexicon element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/tedstrauss/SVN/jtrace/trunk/src/edu/uconn/psy/jtrace/jTRACESchema.xsd line 33)
 * <p>
 * <pre>
 * &lt;element name="lexicon" type="{http://xml.netbeans.org/examples/targetNS}jtLexiconType"/>
 * </pre>
 * 
 */
public interface Lexicon
    extends javax.xml.bind.Element, edu.uconn.psy.jtrace.parser.JtLexiconType
{


}
