//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 01:29:02 EDT 
//


package edu.uconn.psy.jtrace.parser.impl;

public class JtPhonologyTypeImpl implements edu.uconn.psy.jtrace.parser.JtPhonologyType, com.sun.xml.bind.JAXBObject, edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallableObject, edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializable, edu.uconn.psy.jtrace.parser.impl.runtime.ValidatableObject
{

    protected java.lang.String _LanguageName;
    protected edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType _Phonemes;
    public final static java.lang.Class version = (edu.uconn.psy.jtrace.parser.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (edu.uconn.psy.jtrace.parser.JtPhonologyType.class);
    }

    public java.lang.String getLanguageName() {
        return _LanguageName;
    }

    public void setLanguageName(java.lang.String value) {
        _LanguageName = value;
    }

    public edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType getPhonemes() {
        return _Phonemes;
    }

    public void setPhonemes(edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType value) {
        _Phonemes = value;
    }

    public edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingEventHandler createUnmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context) {
        return new edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://xml.netbeans.org/examples/targetNS", "languageName");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _LanguageName), "LanguageName");
        } catch (java.lang.Exception e) {
            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://xml.netbeans.org/examples/targetNS", "phonemes");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Phonemes), "Phonemes");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Phonemes), "Phonemes");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _Phonemes), "Phonemes");
        context.endElement();
    }

    public void serializeAttributes(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (edu.uconn.psy.jtrace.parser.JtPhonologyType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsr\u0000\'com.sun.msv.grammar.trex.ElementPatt"
+"ern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;"
+"xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndecl"
+"aredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.s"
+"un.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/dataty"
+"pe/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/String"
+"Pair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomi"
+"cType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0013L\u0000\nwhi"
+"teSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000"
+" http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.da"
+"tatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.su"
+"n.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com."
+"sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~"
+"\u0000\u0013L\u0000\fnamespaceURIq\u0000~\u0000\u0013xpq\u0000~\u0000\u0017q\u0000~\u0000\u0016sr\u0000\u001dcom.sun.msv.grammar.Ch"
+"oiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.grammar.AttributeE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0007xq\u0000~\u0000\u0003sr\u0000\u0011java.lang"
+".Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u000bppsr\u0000\"com.sun.msv.datat"
+"ype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0010q\u0000~\u0000\u0016t\u0000\u0005QNamesr\u00005com.sun.m"
+"sv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0019q\u0000~\u0000\u001csq\u0000~\u0000\u001dq\u0000~\u0000(q\u0000~\u0000\u0016sr\u0000#com.sun.msv.grammar.SimpleNameClas"
+"s\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0013L\u0000\fnamespaceURIq\u0000~\u0000\u0013xr\u0000\u001dcom.sun"
+".msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.o"
+"rg/2001/XMLSchema-instancesr\u00000com.sun.msv.grammar.Expression"
+"$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000#\u0001psq\u0000~\u0000,t\u0000\flanguage"
+"Namet\u0000)http://xml.netbeans.org/examples/targetNSsq\u0000~\u0000\u0006pp\u0000sq\u0000"
+"~\u0000\u0000ppsq\u0000~\u0000\u0006pp\u0000sq\u0000~\u0000\u001fppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000"
+"~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000$psq\u0000~\u0000!q\u0000~\u0000$psr\u00002com.sun.msv.grammar.Expressio"
+"n$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u00003psr\u0000 com.sun.msv."
+"grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000-q\u0000~\u00002sq\u0000~\u0000,t\u00008edu.uconn"
+".psy.jtrace.parser.JtPhonologyType.PhonemesTypet\u0000+http://jav"
+"a.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u001fppsq\u0000~\u0000!q\u0000~\u0000$pq\u0000~\u0000%q\u0000"
+"~\u0000.q\u0000~\u00002sq\u0000~\u0000,t\u0000\bphonemesq\u0000~\u00006sr\u0000\"com.sun.msv.grammar.Expres"
+"sionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Expres"
+"sionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool"
+"$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lc"
+"om/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0007\u0001pq\u0000~\u0000\nq\u0000~\u0000=q\u0000~\u00008q\u0000~"
+"\u0000\u0005q\u0000~\u0000 q\u0000~\u0000Fq\u0000~\u0000:x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public static class PhonemesTypeImpl implements edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType, com.sun.xml.bind.JAXBObject, edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallableObject, edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializable, edu.uconn.psy.jtrace.parser.impl.runtime.ValidatableObject
    {

        protected com.sun.xml.bind.util.ListImpl _Phoneme;
        public final static java.lang.Class version = (edu.uconn.psy.jtrace.parser.impl.JAXBVersion.class);
        private static com.sun.msv.grammar.Grammar schemaFragment;

        private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
            return (edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType.class);
        }

        protected com.sun.xml.bind.util.ListImpl _getPhoneme() {
            if (_Phoneme == null) {
                _Phoneme = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
            }
            return _Phoneme;
        }

        public java.util.List getPhoneme() {
            return _getPhoneme();
        }

        public edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingEventHandler createUnmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context) {
            return new edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.Unmarshaller(context);
        }

        public void serializeBody(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            int idx1 = 0;
            final int len1 = ((_Phoneme == null)? 0 :_Phoneme.size());
            while (idx1 != len1) {
                context.startElement("http://xml.netbeans.org/examples/targetNS", "phoneme");
                int idx_0 = idx1;
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Phoneme.get(idx_0 ++)), "Phoneme");
                context.endNamespaceDecls();
                int idx_1 = idx1;
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Phoneme.get(idx_1 ++)), "Phoneme");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Phoneme.get(idx1 ++)), "Phoneme");
                context.endElement();
            }
        }

        public void serializeAttributes(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            int idx1 = 0;
            final int len1 = ((_Phoneme == null)? 0 :_Phoneme.size());
            while (idx1 != len1) {
                idx1 += 1;
            }
        }

        public void serializeURIs(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            int idx1 = 0;
            final int len1 = ((_Phoneme == null)? 0 :_Phoneme.size());
            while (idx1 != len1) {
                idx1 += 1;
            }
        }

        public java.lang.Class getPrimaryInterface() {
            return (edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType.class);
        }

        public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
            if (schemaFragment == null) {
                schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.s"
+"un.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expt\u0000 Lcom/sun/msv/gram"
+"mar/Expression;xr\u0000\u001ecom.sun.msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002"
+"L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000"
+"~\u0000\u0002xpppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.m"
+"sv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttribute"
+"sL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sr\u0000\u001fcom.sun.msv.grammar.Sequen"
+"ceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002"
+"L\u0000\u0004exp1q\u0000~\u0000\u0002L\u0000\u0004exp2q\u0000~\u0000\u0002xq\u0000~\u0000\u0003ppsq\u0000~\u0000\u0006pp\u0000sr\u0000\u001dcom.sun.msv.gra"
+"mmar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u000bppsq\u0000~\u0000\u0000sr\u0000\u0011java.lang.Boolean"
+"\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0007xq\u0000~\u0000\u0003q\u0000~\u0000\u0012psr\u00002com.su"
+"n.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0003sq\u0000~\u0000\u0011\u0001psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001d"
+"com.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gr"
+"ammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0017psr\u0000"
+"#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet"
+"\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001exq\u0000~\u0000\u0019t\u0000Dedu.uconn.p"
+"sy.jtrace.parser.JtPhonologyType.PhonemesType.PhonemeTypet\u0000+"
+"http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u000eppsq\u0000~\u0000\u0013q\u0000~"
+"\u0000\u0012psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/re"
+"laxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv"
+"/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.datatype.xsd.QnameT"
+"ype\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\f"
+"namespaceUriq\u0000~\u0000\u001eL\u0000\btypeNameq\u0000~\u0000\u001eL\u0000\nwhiteSpacet\u0000.Lcom/sun/ms"
+"v/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/20"
+"01/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceP"
+"rocessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.Whi"
+"teSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Express"
+"ion$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util"
+".StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001eL\u0000\fnamespaceURIq\u0000~\u0000\u001ex"
+"pq\u0000~\u0000/q\u0000~\u0000.sq\u0000~\u0000\u001dt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-"
+"instanceq\u0000~\u0000\u001csq\u0000~\u0000\u001dt\u0000\u0007phonemet\u0000)http://xml.netbeans.org/exam"
+"ples/targetNSsr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHa"
+"sh;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8"
+"\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/gramma"
+"r/ExpressionPool;xp\u0000\u0000\u0000\u0005\u0001pq\u0000~\u0000\u0010q\u0000~\u0000\fq\u0000~\u0000\u0005q\u0000~\u0000\"q\u0000~\u0000\u000fx"));
            }
            return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
        }

        public static class PhonemeTypeImpl implements edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType.PhonemeType, com.sun.xml.bind.JAXBObject, edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallableObject, edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializable, edu.uconn.psy.jtrace.parser.impl.runtime.ValidatableObject
        {

            protected com.sun.xml.bind.util.ListImpl _DurationScalar;
            protected com.sun.xml.bind.util.ListImpl _AllophonicRelations;
            protected java.lang.String _Symbol;
            protected com.sun.xml.bind.util.ListImpl _Features;
            public final static java.lang.Class version = (edu.uconn.psy.jtrace.parser.impl.JAXBVersion.class);
            private static com.sun.msv.grammar.Grammar schemaFragment;

            private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
                return (edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType.PhonemeType.class);
            }

            protected com.sun.xml.bind.util.ListImpl _getDurationScalar() {
                if (_DurationScalar == null) {
                    _DurationScalar = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
                }
                return _DurationScalar;
            }

            public java.util.List getDurationScalar() {
                return _getDurationScalar();
            }

            protected com.sun.xml.bind.util.ListImpl _getAllophonicRelations() {
                if (_AllophonicRelations == null) {
                    _AllophonicRelations = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
                }
                return _AllophonicRelations;
            }

            public java.util.List getAllophonicRelations() {
                return _getAllophonicRelations();
            }

            public java.lang.String getSymbol() {
                return _Symbol;
            }

            public void setSymbol(java.lang.String value) {
                _Symbol = value;
            }

            protected com.sun.xml.bind.util.ListImpl _getFeatures() {
                if (_Features == null) {
                    _Features = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
                }
                return _Features;
            }

            public java.util.List getFeatures() {
                return _getFeatures();
            }

            public edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingEventHandler createUnmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context) {
                return new edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.PhonemeTypeImpl.Unmarshaller(context);
            }

            public void serializeBody(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
                throws org.xml.sax.SAXException
            {
                int idx1 = 0;
                final int len1 = ((_DurationScalar == null)? 0 :_DurationScalar.size());
                int idx2 = 0;
                final int len2 = ((_AllophonicRelations == null)? 0 :_AllophonicRelations.size());
                int idx4 = 0;
                final int len4 = ((_Features == null)? 0 :_Features.size());
                context.startElement("http://xml.netbeans.org/examples/targetNS", "symbol");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _Symbol), "Symbol");
                } catch (java.lang.Exception e) {
                    edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
                context.startElement("http://xml.netbeans.org/examples/targetNS", "features");
                int idx_2 = idx4;
                while (idx_2 != len4) {
                    try {
                        idx_2 += 1;
                    } catch (java.lang.Exception e) {
                        edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                }
                context.endNamespaceDecls();
                int idx_3 = idx4;
                while (idx_3 != len4) {
                    try {
                        idx_3 += 1;
                    } catch (java.lang.Exception e) {
                        edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                }
                context.endAttributes();
                while (idx4 != len4) {
                    try {
                        context.text(javax.xml.bind.DatatypeConverter.printDecimal(((java.math.BigDecimal) _Features.get(idx4 ++))), "Features");
                    } catch (java.lang.Exception e) {
                        edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                }
                context.endElement();
                if (((_DurationScalar == null)? 0 :_DurationScalar.size())>= 1) {
                    context.startElement("http://xml.netbeans.org/examples/targetNS", "durationScalar");
                    int idx_4 = idx1;
                    while (idx_4 != len1) {
                        try {
                            idx_4 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                    context.endNamespaceDecls();
                    int idx_5 = idx1;
                    while (idx_5 != len1) {
                        try {
                            idx_5 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                    context.endAttributes();
                    while (idx1 != len1) {
                        try {
                            context.text(javax.xml.bind.DatatypeConverter.printDecimal(((java.math.BigDecimal) _DurationScalar.get(idx1 ++))), "DurationScalar");
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                    context.endElement();
                }
                if (((_AllophonicRelations == null)? 0 :_AllophonicRelations.size())>= 1) {
                    context.startElement("http://xml.netbeans.org/examples/targetNS", "allophonicRelations");
                    int idx_6 = idx2;
                    while (idx_6 != len2) {
                        try {
                            idx_6 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                    context.endNamespaceDecls();
                    int idx_7 = idx2;
                    while (idx_7 != len2) {
                        try {
                            idx_7 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                    context.endAttributes();
                    while (idx2 != len2) {
                        try {
                            context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean)((java.lang.Boolean) _AllophonicRelations.get(idx2 ++)).booleanValue())), "AllophonicRelations");
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                    context.endElement();
                }
            }

            public void serializeAttributes(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
                throws org.xml.sax.SAXException
            {
                int idx1 = 0;
                final int len1 = ((_DurationScalar == null)? 0 :_DurationScalar.size());
                int idx2 = 0;
                final int len2 = ((_AllophonicRelations == null)? 0 :_AllophonicRelations.size());
                int idx4 = 0;
                final int len4 = ((_Features == null)? 0 :_Features.size());
                while (idx4 != len4) {
                    try {
                        idx4 += 1;
                    } catch (java.lang.Exception e) {
                        edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                }
                if (((_DurationScalar == null)? 0 :_DurationScalar.size())>= 1) {
                    while (idx1 != len1) {
                        try {
                            idx1 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                }
                if (((_AllophonicRelations == null)? 0 :_AllophonicRelations.size())>= 1) {
                    while (idx2 != len2) {
                        try {
                            idx2 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                }
            }

            public void serializeURIs(edu.uconn.psy.jtrace.parser.impl.runtime.XMLSerializer context)
                throws org.xml.sax.SAXException
            {
                int idx1 = 0;
                final int len1 = ((_DurationScalar == null)? 0 :_DurationScalar.size());
                int idx2 = 0;
                final int len2 = ((_AllophonicRelations == null)? 0 :_AllophonicRelations.size());
                int idx4 = 0;
                final int len4 = ((_Features == null)? 0 :_Features.size());
                while (idx4 != len4) {
                    try {
                        idx4 += 1;
                    } catch (java.lang.Exception e) {
                        edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                }
                if (((_DurationScalar == null)? 0 :_DurationScalar.size())>= 1) {
                    while (idx1 != len1) {
                        try {
                            idx1 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                }
                if (((_AllophonicRelations == null)? 0 :_AllophonicRelations.size())>= 1) {
                    while (idx2 != len2) {
                        try {
                            idx2 += 1;
                        } catch (java.lang.Exception e) {
                            edu.uconn.psy.jtrace.parser.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    }
                }
            }

            public java.lang.Class getPrimaryInterface() {
                return (edu.uconn.psy.jtrace.parser.JtPhonologyType.PhonemesType.PhonemeType.class);
            }

            public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
                if (schemaFragment == null) {
                    schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.grammar."
+"trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gr"
+"ammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000s"
+"q\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLor"
+"g/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun"
+"/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatype.xsd.St"
+"ringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype."
+"xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd"
+".ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatat"
+"ypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btyp"
+"eNameq\u0000~\u0000\u0015L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpa"
+"ceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr"
+"\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000"
+"\u0002L\u0000\tlocalNameq\u0000~\u0000\u0015L\u0000\fnamespaceURIq\u0000~\u0000\u0015xpq\u0000~\u0000\u0019q\u0000~\u0000\u0018sr\u0000\u001dcom.su"
+"n.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.gr"
+"ammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\txq\u0000"
+"~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\rppsr\u0000\"c"
+"om.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0012q\u0000~\u0000\u0018t\u0000\u0005QN"
+"amesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001bq\u0000~\u0000\u001esq\u0000~\u0000\u001fq\u0000~\u0000*q\u0000~\u0000\u0018sr\u0000#com.sun.msv.gramma"
+"r.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0015L\u0000\fnamespaceURI"
+"q\u0000~\u0000\u0015xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000"
+")http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gr"
+"ammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000%\u0001ps"
+"q\u0000~\u0000.t\u0000\u0006symbolt\u0000)http://xml.netbeans.org/examples/targetNSsq"
+"\u0000~\u0000\bpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rppsr\u0000\'com.sun.msv.datatype.xsd.MaxLengt"
+"hFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tmaxLengthxr\u00009com.sun.msv.datatype.xsd.Da"
+"taTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.dat"
+"atype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012need"
+"ValueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSData"
+"typeImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/Concret"
+"eType;L\u0000\tfacetNameq\u0000~\u0000\u0015xq\u0000~\u0000\u0014q\u0000~\u00008pq\u0000~\u0000,\u0000\u0001sr\u0000\'com.sun.msv.da"
+"tatype.xsd.MinLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tminLengthxq\u0000~\u0000=q\u0000~\u00008p"
+"q\u0000~\u0000,\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.ListType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bit"
+"emTypeq\u0000~\u0000?xq\u0000~\u0000\u0013q\u0000~\u00008t\u0000\flistBaseTypeq\u0000~\u0000,sr\u0000#com.sun.msv.da"
+"tatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0012q\u0000~\u0000\u0018t\u0000\u0007decimalq\u0000~\u0000,q\u0000"
+"~\u0000Et\u0000\tminLength\u0000\u0000\u0000\u0001q\u0000~\u0000Et\u0000\tmaxLength\u0000\u0000\u0003\u00e8q\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0014listBa"
+"seType-derivedq\u0000~\u00008sq\u0000~\u0000!ppsq\u0000~\u0000#q\u0000~\u0000&pq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000."
+"t\u0000\bfeaturesq\u0000~\u00008sq\u0000~\u0000!ppsq\u0000~\u0000\bq\u0000~\u0000&p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rppsq\u0000~\u0000<q"
+"\u0000~\u00008pq\u0000~\u0000,\u0000\u0001sq\u0000~\u0000Bq\u0000~\u00008pq\u0000~\u0000,\u0000\u0000q\u0000~\u0000Eq\u0000~\u0000Eq\u0000~\u0000J\u0000\u0000\u0000\u0001q\u0000~\u0000Eq\u0000~\u0000K"
+"\u0000\u0000\u0003\u00e8q\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0014listBaseType-derivedq\u0000~\u00008sq\u0000~\u0000!ppsq\u0000~\u0000#q\u0000~"
+"\u0000&pq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000\u000edurationScalarq\u0000~\u00008q\u0000~\u00004sq\u0000~\u0000!pps"
+"q\u0000~\u0000\bq\u0000~\u0000&p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rppsq\u0000~\u0000<q\u0000~\u00008pq\u0000~\u0000,\u0000\u0001sq\u0000~\u0000Bq\u0000~\u00008pq"
+"\u0000~\u0000,\u0000\u0000sq\u0000~\u0000Dq\u0000~\u00008t\u0000\u0010listBaseTypeBoolq\u0000~\u0000,sr\u0000$com.sun.msv.dat"
+"atype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0012q\u0000~\u0000\u0018t\u0000\u0007booleanq\u0000~\u0000,q\u0000"
+"~\u0000dq\u0000~\u0000J\u0000\u0000\u0000\u0001q\u0000~\u0000dq\u0000~\u0000K\u0000\u0000\u0003\u00e8q\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0018listBaseTypeBool-der"
+"ivedq\u0000~\u00008sq\u0000~\u0000!ppsq\u0000~\u0000#q\u0000~\u0000&pq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000\u0013allopho"
+"nicRelationsq\u0000~\u00008q\u0000~\u00004sr\u0000\"com.sun.msv.grammar.ExpressionPool"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool"
+"$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedH"
+"ash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/m"
+"sv/grammar/ExpressionPool;xp\u0000\u0000\u0000\r\u0001pq\u0000~\u0000Rq\u0000~\u0000\fq\u0000~\u0000:q\u0000~\u0000`q\u0000~\u0000^q"
+"\u0000~\u0000Tq\u0000~\u0000\u0007q\u0000~\u0000\"q\u0000~\u0000Nq\u0000~\u0000Zq\u0000~\u0000kq\u0000~\u0000\u0005q\u0000~\u0000\u0006x"));
                }
                return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
            }

            public class Unmarshaller
                extends edu.uconn.psy.jtrace.parser.impl.runtime.AbstractUnmarshallingEventHandlerImpl
            {


                public Unmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context) {
                    super(context, "----L--L--L--");
                }

                protected Unmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context, int startState) {
                    this(context);
                    state = startState;
                }

                public java.lang.Object owner() {
                    return edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.PhonemeTypeImpl.this;
                }

                public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                    throws org.xml.sax.SAXException
                {
                    int attIdx;
                    outer:
                    while (true) {
                        switch (state) {
                            case  0 :
                                if (("symbol" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.pushAttributes(__atts, true);
                                    state = 1;
                                    return ;
                                }
                                break;
                            case  3 :
                                if (("features" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.pushAttributes(__atts, true);
                                    state = 4;
                                    return ;
                                }
                                break;
                            case  9 :
                                if (("allophonicRelations" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.pushAttributes(__atts, true);
                                    state = 10;
                                    return ;
                                }
                                state = 12;
                                continue outer;
                            case  6 :
                                if (("durationScalar" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.pushAttributes(__atts, true);
                                    state = 7;
                                    return ;
                                }
                                state = 9;
                                continue outer;
                            case  12 :
                                revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                                return ;
                        }
                        super.enterElement(___uri, ___local, ___qname, __atts);
                        break;
                    }
                }

                public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                    throws org.xml.sax.SAXException
                {
                    int attIdx;
                    outer:
                    while (true) {
                        switch (state) {
                            case  2 :
                                if (("symbol" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.popAttributes();
                                    state = 3;
                                    return ;
                                }
                                break;
                            case  9 :
                                state = 12;
                                continue outer;
                            case  5 :
                                if (("features" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.popAttributes();
                                    state = 6;
                                    return ;
                                }
                                break;
                            case  6 :
                                state = 9;
                                continue outer;
                            case  11 :
                                if (("allophonicRelations" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.popAttributes();
                                    state = 12;
                                    return ;
                                }
                                break;
                            case  8 :
                                if (("durationScalar" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                    context.popAttributes();
                                    state = 9;
                                    return ;
                                }
                                break;
                            case  12 :
                                revertToParentFromLeaveElement(___uri, ___local, ___qname);
                                return ;
                        }
                        super.leaveElement(___uri, ___local, ___qname);
                        break;
                    }
                }

                public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                    throws org.xml.sax.SAXException
                {
                    int attIdx;
                    outer:
                    while (true) {
                        switch (state) {
                            case  9 :
                                state = 12;
                                continue outer;
                            case  6 :
                                state = 9;
                                continue outer;
                            case  12 :
                                revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                                return ;
                        }
                        super.enterAttribute(___uri, ___local, ___qname);
                        break;
                    }
                }

                public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                    throws org.xml.sax.SAXException
                {
                    int attIdx;
                    outer:
                    while (true) {
                        switch (state) {
                            case  9 :
                                state = 12;
                                continue outer;
                            case  6 :
                                state = 9;
                                continue outer;
                            case  12 :
                                revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                                return ;
                        }
                        super.leaveAttribute(___uri, ___local, ___qname);
                        break;
                    }
                }

                public void handleText(final java.lang.String value)
                    throws org.xml.sax.SAXException
                {
                    int attIdx;
                    outer:
                    while (true) {
                        try {
                            switch (state) {
                                case  10 :
                                    eatText1(value);
                                    state = 11;
                                    return ;
                                case  7 :
                                    eatText2(value);
                                    state = 8;
                                    return ;
                                case  4 :
                                    eatText3(value);
                                    state = 5;
                                    return ;
                                case  9 :
                                    state = 12;
                                    continue outer;
                                case  5 :
                                    eatText3(value);
                                    state = 5;
                                    return ;
                                case  6 :
                                    state = 9;
                                    continue outer;
                                case  11 :
                                    eatText1(value);
                                    state = 11;
                                    return ;
                                case  8 :
                                    eatText2(value);
                                    state = 8;
                                    return ;
                                case  1 :
                                    eatText4(value);
                                    state = 2;
                                    return ;
                                case  12 :
                                    revertToParentFromText(value);
                                    return ;
                            }
                        } catch (java.lang.RuntimeException e) {
                            handleUnexpectedTextException(value, e);
                        }
                        break;
                    }
                }

                private void eatText1(final java.lang.String value)
                    throws org.xml.sax.SAXException
                {
                    try {
                        _getAllophonicRelations().add(new java.lang.Boolean(javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value))));
                    } catch (java.lang.Exception e) {
                        handleParseConversionException(e);
                    }
                }

                private void eatText2(final java.lang.String value)
                    throws org.xml.sax.SAXException
                {
                    try {
                        _getDurationScalar().add(javax.xml.bind.DatatypeConverter.parseDecimal(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value)));
                    } catch (java.lang.Exception e) {
                        handleParseConversionException(e);
                    }
                }

                private void eatText3(final java.lang.String value)
                    throws org.xml.sax.SAXException
                {
                    try {
                        _getFeatures().add(javax.xml.bind.DatatypeConverter.parseDecimal(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value)));
                    } catch (java.lang.Exception e) {
                        handleParseConversionException(e);
                    }
                }

                private void eatText4(final java.lang.String value)
                    throws org.xml.sax.SAXException
                {
                    try {
                        _Symbol = value;
                    } catch (java.lang.Exception e) {
                        handleParseConversionException(e);
                    }
                }

            }

        }

        public class Unmarshaller
            extends edu.uconn.psy.jtrace.parser.impl.runtime.AbstractUnmarshallingEventHandlerImpl
        {


            public Unmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context) {
                super(context, "----");
            }

            protected Unmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context, int startState) {
                this(context);
                state = startState;
            }

            public java.lang.Object owner() {
                return edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.this;
            }

            public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  0 :
                            if (("phoneme" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                context.pushAttributes(__atts, false);
                                state = 1;
                                return ;
                            }
                            break;
                        case  3 :
                            if (("phoneme" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                context.pushAttributes(__atts, false);
                                state = 1;
                                return ;
                            }
                            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        case  1 :
                            if (("symbol" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                _getPhoneme().add(((edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.PhonemeTypeImpl) spawnChildFromEnterElement((edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.PhonemeTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                                return ;
                            }
                            break;
                    }
                    super.enterElement(___uri, ___local, ___qname, __atts);
                    break;
                }
            }

            public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  3 :
                            revertToParentFromLeaveElement(___uri, ___local, ___qname);
                            return ;
                        case  2 :
                            if (("phoneme" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                                context.popAttributes();
                                state = 3;
                                return ;
                            }
                            break;
                    }
                    super.leaveElement(___uri, ___local, ___qname);
                    break;
                }
            }

            public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  3 :
                            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                            return ;
                    }
                    super.enterAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  3 :
                            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                            return ;
                    }
                    super.leaveAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    try {
                        switch (state) {
                            case  3 :
                                revertToParentFromText(value);
                                return ;
                        }
                    } catch (java.lang.RuntimeException e) {
                        handleUnexpectedTextException(value, e);
                    }
                    break;
                }
            }

        }

    }

    public class Unmarshaller
        extends edu.uconn.psy.jtrace.parser.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context) {
            super(context, "-------");
        }

        protected Unmarshaller(edu.uconn.psy.jtrace.parser.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        if (("phoneme" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                            _Phonemes = ((edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl) spawnChildFromEnterElement((edu.uconn.psy.jtrace.parser.impl.JtPhonologyTypeImpl.PhonemesTypeImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  0 :
                        if (("languageName" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("phonemes" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        break;
                    case  6 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  5 :
                        if (("phonemes" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("languageName" == ___local)&&("http://xml.netbeans.org/examples/targetNS" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  6 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  6 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _LanguageName = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
